load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "fsdb_cgo_pub_sub_wrapper",
    srcs = [
        "FsdbCgoPubSubWrapper.cpp",
    ],
    headers = [
        "FsdbCgoPubSubWrapper.h",
        "fsdb_cgo_api.h",
    ],
    # Vendor-shipped archive exports only FSDB_CGO_API entry points. Force
    # static linkage so test binaries (which use the C++ class directly) can
    # still see the hidden symbols inside the same archive.
    compiler_flags = [
        "-fvisibility=hidden",
        "-fvisibility-inlines-hidden",
    ],
    preferred_linkage = "static",
    deps = [
        "//fboss/agent:switch_state-cpp2-types",
        "//fboss/fsdb/if:fsdb-cpp2-types",
        "//fboss/fsdb/if:fsdb_model",
        "//fboss/lib/thrift_service_client:thrift-service-client",
        "//folly:string",
        "//folly/init:init",
        "//folly/init:phase",
        "//folly/logging:logging",
        "//folly/synchronization:call_once",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
    exported_deps = [
        "//fboss/fsdb/client:fsdb_pub_sub",
        "//fboss/fsdb/if:fsdb_oper-cpp2-types",
        "//folly:fbstring",
        "//folly/concurrency:dynamic_bounded_queue",
    ],
    external_deps = ["gflags"],
    exported_external_deps = [
        "gflags",
    ],
)
