load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fboss_distro")

python_library(
    name = "artifact",
    srcs = ["artifact.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
    deps = [
        "//fboss/github/fboss-image/distro_cli/lib:exceptions",
        "//fboss/github/fboss-image/distro_cli/lib:paths",
    ],
)

python_library(
    name = "cli",
    srcs = ["cli.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
)

python_library(
    name = "constants",
    srcs = ["constants.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
)

python_library(
    name = "distro_infra",
    srcs = ["distro_infra.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
    deps = [
        "//fboss/github/fboss-image/distro_cli/lib:exceptions",
        "//fboss/github/fboss-image/distro_cli/lib/docker:docker",
    ],
)

python_library(
    name = "exceptions",
    srcs = ["exceptions.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
)

python_library(
    name = "paths",
    srcs = ["paths.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
)

python_library(
    name = "device_update",
    srcs = ["device_update.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
    deps = [
        ":exceptions",
        ":manifest",
        "//fboss/github/fboss-image/distro_cli/builder:builder",
    ],
)

python_library(
    name = "download",
    srcs = ["download.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
    deps = [
        ":artifact",
        ":constants",
        ":exceptions",
    ],
)

python_library(
    name = "execute",
    srcs = ["execute.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
    deps = [
        ":exceptions",
        "//fboss/github/fboss-image/distro_cli/lib/docker:docker",
    ],
)

python_library(
    name = "manifest",
    srcs = ["manifest.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
    deps = [":constants"],
)

python_library(
    name = "artifact_versions",
    srcs = ["artifact_versions.py"],
    base_module = "distro_cli.lib",
    labels = ["autodeps2_generated"],
)

python_library(
    name = "version_file",
    srcs = ["version_file.py"],
    base_module = "distro_cli.lib",
    deps = ["//fboss/github/fboss-image/distro_cli/lib:artifact_versions"],
)
