load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_platform")

cpp_unittest(
    name = "cross_config_validator_test",
    srcs = [
        "CrossConfigValidatorTest.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//fboss/platform/config_lib:cross_config_validator",
    ],
)
