load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_platform")

cpp_unittest(
    name = "cross_config_validator_test",
    srcs = [
        "CrossConfigValidatorTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//fboss/platform/config_lib:cross_config_validator",
    ],
)
