load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "thrift-service-client",
    srcs = [
        "ConnectionOptions.cpp",
        "ThriftServiceClient.cpp",
        "facebook/ConnectionOptions.cpp",
        "facebook/ThriftServiceClient.cpp",
    ],
    headers = [
        "ConnectionOptions.h",
        "ThriftServiceClient.h",
    ],
    exported_deps = [
        "//common/fbwhoami:fb_who_am_i",
        "//common/services/cpp:facebook_identity_verifier",
        "//common/services/cpp:tls_constants",
        "//configerator/structs/infrasec/if:acl-cpp2-types",
        "//fboss/agent/if:ctrl-cpp2-clients",
        "//fboss/fsdb/common:flags",
        "//fboss/fsdb/if:fsdb-cpp2-services",
        "//fboss/qsfp_service/if:qsfp-cpp2-clients",
        "//folly:network_address",
        "//folly/io:socket_option_map",
        "//folly/io/async:async_base",
        "//folly/io/async:async_socket_transport",
        "//folly/io/async:async_ssl_socket",
        "//folly/io/async:ssl_context",
        "//infrasec/authorization:base_identity_util",
        "//neteng/fboss/tools/build_info/server/if:fboss_build_info_if-cpp2-services",
        "//security/ca/lib:cert_path_picker",
        "//thrift/lib/cpp2/async:header_client_channel",
        "//thrift/lib/cpp2/async:rocket_client_channel",
    ],
)
