load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_platform")

# Thrift definitions for platform checks data structures
thrift_library(
    name = "check_types",
    languages = [
        "cpp2",
    ],
    thrift_srcs = {"check_types.thrift": []},
)

cpp_library(
    name = "platform_check",
    srcs = [
        "CommandLog.cpp",
        "PlatformCheck.cpp",
    ],
    headers = [
        "CommandLog.h",
        "PlatformCheck.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/platform/config_lib:config_lib",
        "//folly/logging:logging",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
    exported_deps = [
        ":check_types-cpp2-types",
        ":host",
        "//fboss/platform/platform_manager:platform_manager_config-cpp2-types",
    ],
)

cpp_library(
    name = "host",
    srcs = [
        "Host.cpp",
        "LocalHost.cpp",
    ],
    headers = [
        "Host.h",
        "LocalHost.h",
    ],
    deps = [
        "//folly:file_util",
        "//folly:string",
        "//folly:subprocess",
        "//folly/logging:logging",
        "//folly/system:shell",
    ],
)

cpp_library(
    name = "remote_host",
    srcs = [
        "RemoteHost.cpp",
    ],
    headers = [
        "RemoteHost.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/platform/helpers:expect_session",
        "//folly:string",
        "//folly/logging:logging",
        "//folly/system:shell",
    ],
    exported_deps = [
        ":host",
    ],
)

cpp_library(
    name = "platform_name",
    srcs = [
        "PlatformName.cpp",
    ],
    headers = [
        "PlatformName.h",
    ],
    deps = [
        "//fboss/platform/helpers:platform_name_lib",
        "//folly:string",
        "//folly/logging:logging",
    ],
    exported_deps = [
        ":host",
    ],
)

cpp_library(
    name = "mock_host",
    headers = [
        "tests/MockHost.h",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gmock",
        ":host",
    ],
)

cpp_library(
    name = "platform_checks",
    srcs = [
        "HostEeprom.cpp",
        "checks/CommandCheck.cpp",
        "checks/KernelVersionCheck.cpp",
        "checks/MacAddressCheck.cpp",
        "checks/ManagementPlaneChecks.cpp",
        "checks/PciDeviceCheck.cpp",
        "checks/PowerResetCheck.cpp",
        "checks/i801SmbusTimeoutCheck.cpp",
    ],
    headers = [
        "HostEeprom.h",
        "checks/BmcReachableCheck.h",
        "checks/CommandCheck.h",
        "checks/KernelVersionCheck.h",
        "checks/MacAddressCheck.h",
        "checks/ManagementPlaneChecks.h",
        "checks/PciDeviceCheck.h",
        "checks/PowerResetCheck.h",
        "checks/i801SmbusTimeoutCheck.h",
    ],
    deps = [
        "fbsource//third-party/re2:re2",
        "//common/config:configerator",
        "//configerator/structs/fboss/fboss_platform:kernel_versions-cpp2-types",
        "//fboss/platform/weutil:config_utils_lib",
        "//folly:string",
        "//folly/json:dynamic",
        "//folly/logging:logging",
        "//folly/system:shell",
    ],
    exported_deps = [
        ":host",
        ":platform_check",
        "//fboss/platform/platform_manager:platform_manager_config-cpp2-types",
        "//folly:network_address",
    ],
)

cpp_unittest(
    name = "mac_address_check_test",
    srcs = [
        "tests/MacAddressCheckTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":mock_host",
        ":platform_checks",
    ],
)

cpp_unittest(
    name = "pci_device_check_test",
    srcs = [
        "tests/PciDeviceCheckTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":mock_host",
        ":platform_checks",
    ],
)

cpp_unittest(
    name = "power_reset_check_test",
    srcs = [
        "tests/PowerResetCheckTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":mock_host",
        ":platform_checks",
    ],
)

cpp_unittest(
    name = "kernel_version_check_test",
    srcs = [
        "tests/KernelVersionCheckTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":platform_checks",
    ],
)

cpp_unittest(
    name = "i801_smbus_timeout_check_test",
    srcs = [
        "tests/i801SmbusTimeoutCheckTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":mock_host",
        ":platform_checks",
    ],
)

cpp_unittest(
    name = "local_host_test",
    srcs = [
        "tests/LocalHostTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":host",
        "//folly:file_util",
        "//folly/testing:test_util",
    ],
)

cpp_unittest(
    name = "remote_host_test",
    srcs = [
        "tests/RemoteHostTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":remote_host",
        "//folly/testing:test_util",
    ],
)

cpp_unittest(
    name = "platform_name_test",
    srcs = [
        "tests/PlatformNameTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":mock_host",
        ":platform_name",
    ],
)

cpp_unittest(
    name = "bmc_reachable_check_test",
    srcs = [
        "tests/BmcReachableCheckTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":mock_host",
        ":platform_checks",
    ],
)

cpp_unittest(
    name = "management_plane_checks_test",
    srcs = [
        "tests/ManagementPlaneChecksTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":mock_host",
        ":platform_checks",
    ],
)
