load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "platform",
    srcs = [
        "SimPlatform.cpp",
        "SimPlatformMapping.cpp",
        "SimPlatformPort.cpp",
        "SimSwitch.cpp",
    ],
    deps = [
        "//fboss/agent:fboss-error",
        "//fboss/agent:handler",
        "//fboss/agent/hw/mock:pkt",
        "//fboss/agent/state:state",
        "//fboss/lib/platforms:product-info",
        "//folly:conv",
        "//folly:memory",
        "//folly/json:dynamic",
    ],
    exported_deps = [
        "//fboss/agent:fboss-types",
        "//fboss/agent:hw_switch",
        "//fboss/agent:platform_base",
        "//fboss/agent:platform_config-cpp2-types",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent/platforms/common:platform_mapping",
    ],
)
