load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_platform")

cpp_library(
    name = "utils",
    srcs = [
        "TestUtils.cpp",
    ],
    exported_deps = [
        "//fboss/platform/sensor_service:service",
        "//folly:file_util",
        "//folly/testing:test_util",
    ],
)

cpp_unittest(
    name = "sensor_service_sw_test",
    srcs = [
        "SensorServiceImplTest.cpp",
        "SensorServiceThriftHandlerTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":utils",
        "//fb303:service_data",
        "//fboss/platform/sensor_service:core",
        "//fboss/platform/sensor_service:service",
        "//fboss/platform/sensor_service:utils",
        "//folly:file_util",
        "//folly/logging:logging",
        "//folly/testing:test_util",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)

cpp_unittest(
    name = "utils_tests",
    srcs = [
        "UtilsTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/sensor_service:utils",
    ],
)

cpp_unittest(
    name = "config_validator_test",
    srcs = [
        "ConfigValidatorTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/sensor_service:config_validator",
        "//fboss/platform/sensor_service/utilities:power_config_utils",
    ],
)

cpp_unittest(
    name = "sensor_service_asic_temp_test",
    srcs = [
        "SensorServiceImplAsicTempTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//fb303:service_data",
        "//fboss/platform/helpers:mock_platform_utils",
        "//fboss/platform/sensor_service:service",
        "//fboss/platform/sensor_service:utils",
    ],
)

cpp_unittest(
    name = "sensor_service_power_consumption_test",
    srcs = [
        "SensorServiceImplPowerConsumptionTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fb303:service_data",
        "//fboss/platform/sensor_service:service",
        "//folly:file_util",
    ],
)

cpp_unittest(
    name = "sensor_service_temperature_test",
    srcs = [
        "SensorServiceImplTemperatureTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fb303:service_data",
        "//fboss/platform/sensor_service:service",
        "//folly:file_util",
    ],
)

cpp_unittest(
    name = "sensor_service_input_voltage_test",
    srcs = [
        "SensorServiceImplInputVoltageTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fb303:service_data",
        "//fboss/platform/sensor_service:service",
        "//folly:file_util",
    ],
)

cpp_unittest(
    name = "pmunit_info_fetcher_test",
    srcs = [
        "PmUnitInfoFetcherTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//fboss/platform/platform_manager:platform_manager_service-cpp2-services",
        "//fboss/platform/platform_manager:platform_manager_service-cpp2-types",
        "//fboss/platform/sensor_service:pmunit_info_fetcher",
    ],
)
