load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("fboss_agent_push")

thrift_library(
    name = "model",
    languages = [
        "cpp2",
    ],
    thrift_cpp2_options = "json",
    thrift_srcs = {"model.thrift": []},
    deps = [
        "//configerator/structs/neteng/bgp_policy/thrift:nsf_policy",
        "//fboss/agent/if:common",
    ],
)
