load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "packet",
    srcs = [
        "ArpHdr.cpp",
        "DHCPv4Packet.cpp",
        "DHCPv6Packet.cpp",
        "EthHdr.cpp",
        "ICMPExtHdr.cpp",
        "ICMPHdr.cpp",
        "IPv4Hdr.cpp",
        "IPv6Hdr.cpp",
        "LlcHdr.cpp",
        "MPLSHdr.cpp",
        "NDP.cpp",
        "NDPRouterAdvertisement.cpp",
        "PTPHeader.cpp",
        "PktUtil.cpp",
        "TCPHeader.cpp",
        "UDPHeader.cpp",
    ],
    headers = [
        "ArpHdr.h",
        "DHCPv4Packet.h",
        "DHCPv6Packet.h",
        "EthHdr.h",
        "ICMPExtHdr.h",
        "ICMPHdr.h",
        "IPv4Hdr.h",
        "IPv6Hdr.h",
        "LlcHdr.h",
        "MPLSHdr.h",
        "NDP.h",
        "NDPRouterAdvertisement.h",
        "PTPHeader.h",
        "PktUtil.h",
        "TCPHeader.h",
        "UDPHeader.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/agent:dhcpv4_options_of_interest",
        "//fboss/agent:fboss-error",
        "//fboss/agent:stats",
        "//folly/lang:bits",
        "//folly/logging:logging",
    ],
    exported_deps = [
        ":ether_type",
        ":hdr_parse_error",
        ":ipproto",
        "//fboss/agent:fboss-types",
        "//fboss/agent:utils",
        "//folly:conv",
        "//folly:network_address",
        "//folly:string",
        "//folly/io:iobuf",
    ],
)

cpp_library(
    name = "sflow_structs",
    srcs = [
        "SflowStructs.cpp",
    ],
    headers = [
        "SflowStructs.h",
    ],
    exported_deps = [
        "//folly:exception_string",
        "//folly:network_address",
        "//folly/io:iobuf",
    ],
)

cpp_library(
    name = "ipfix_header",
    srcs = [
        "IpfixHeader.cpp",
    ],
    headers = [
        "IpfixHeader.h",
    ],
    deps = [":hdr_parse_error"],
    exported_deps = [
        "//folly/io:iobuf",
    ],
)

cpp_library(
    name = "pktutil",
    srcs = [
        "PktUtil.cpp",
    ],
    headers = [
        "PktUtil.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/agent:fboss-error",
        "//folly/io:iobuf",
    ],
    exported_deps = [
        "//folly:network_address",
    ],
)

cpp_library(
    name = "packet_factory",
    srcs = [
        "EthFrame.cpp",
        "IPPacket.cpp",
        "MPLSPacket.cpp",
        "PktFactory.cpp",
        "TCPPacket.cpp",
        "UDPDatagram.cpp",
    ],
    headers = [
        "EthFrame.h",
        "IPPacket.h",
        "MPLSPacket.h",
        "PktFactory.h",
        "TCPPacket.h",
        "UDPDatagram.h",
    ],
    deps = [
        ":ipproto",
        "//common/logging:logging",
        "//fboss/agent:fboss-error",
        "//fboss/agent:hw_switch",
        "//folly:network_address",
    ],
    exported_deps = [
        ":ether_type",
        ":packet",
        ":sflow_structs",
        "//fboss/agent:fboss-types",
        "//fboss/agent:packet",
        "//folly/io:iobuf",
    ],
)

cpp_library(
    name = "ether_type",
    headers = ["Ethertype.h"],
)

cpp_library(
    name = "ipproto",
    headers = ["IPProto.h"],
)

cpp_library(
    name = "hdr_parse_error",
    headers = ["HdrParseError.h"],
)
