load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_agent_push")

cpp_unittest(
    name = "fsdb_server_tests",
    srcs = [
        "FsdbOperTreeMetadataTrackerTest.cpp",
    ],
    deps = [
        "//fboss/fsdb/server:fsdb_oper_metadata_tracker",
    ],
)
