load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_agent_push")

cpp_unittest(
    name = "fsdb_server_tests",
    srcs = [
        "FsdbOperTreeMetadataTrackerTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/fsdb/server:fsdb_oper_metadata_tracker",
    ],
)
