# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

# pyre-strict
load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fboss_agent_push")

python_library(
    name = "conveyor_analyzer_lib",
    srcs = [
        "__init__.py",
        "cli.py",
    ],
    deps = ["fbsource//third-party/pypi/click:click"],
)

python_binary(
    name = "fboss_conveyor",
    srcs = ["fboss_conveyor.py"],
    main_function = "fboss.scripts.conveyor_analyzer.cli.main",
    typing = True,
    deps = [
        ":conveyor_analyzer_lib",
    ],
)
