load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("fboss_optics_phy")

thrift_library(
    name = "hal_test_config",
    languages = ["cpp2"],
    thrift_cpp2_options = "json",
    thrift_srcs = {"hal_test_config.thrift": []},
    deps = [
        "//fboss/qsfp_service/if:transceiver",
    ],
)

cpp_library(
    name = "bsp_transceiver_impl",
    srcs = ["BspTransceiverImpl.cpp"],
    headers = ["BspTransceiverImpl.h"],
    exported_deps = [
        "//fboss/lib/bsp:bsp_core",
        "//fboss/lib/bsp:bsp_platform_mapping-cpp2-types",
        "//fboss/qsfp_service/module:firmware_upgrader",
    ],
)

cpp_library(
    name = "hal_test_utils",
    srcs = ["HalTestUtils.cpp"],
    headers = ["HalTestUtils.h"],
    exported_deps = [
        ":bsp_transceiver_impl",
        ":hal_test_config-cpp2-types",
        "//fboss/agent:fboss-error",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/lib/bsp:bsp_platform_mapping-cpp2-types",
        "//fboss/qsfp_service/if:transceiver-cpp2-types",
        "//fboss/qsfp_service/module:qsfp-module",
        "//folly:conv",
        "//folly:file_util",
        "//folly:format",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)

cpp_library(
    name = "hal_test_base",
    srcs = ["HalTest.cpp"],
    headers = ["HalTest.h"],
    exported_deps = [
        "fbsource//third-party/googletest:gtest",
        ":hal_test_config-cpp2-types",
        ":hal_test_utils",
        "//fboss/agent:fboss-error",
        "//fboss/qsfp_service/module:qsfp-module",
        "//folly/logging:logging",
    ],
)

cpp_binary(
    name = "qsfp_hal_test",
    srcs = [
        "HalTestApplicationModes.cpp",
        "HalTestModuleAdvertisement.cpp",
        "HalTestModuleInit.cpp",
        "Main.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        ":hal_test_base",
        ":hal_test_config-cpp2-types",
        ":hal_test_utils",
        "//fboss/qsfp_service/if:transceiver-cpp2-types",
        "//fboss/qsfp_service/module:qsfp-module",
        "//folly/init:init",
        "//thrift/lib/cpp/util:enum_utils",
    ],
)
