load("@fbcode_macros//build_defs:native_rules.bzl", "buck_filegroup")

oncall("fboss_optics_phy")

buck_filegroup(
    name = "vendor_platform_descriptors",
    srcs = glob(["*/*/*.json"]),
    visibility = [
        "//fboss/agent/fbpkg/...",
        "//fboss/led_service/fbpkg/...",
        "//netos/services/fboss_sw_agent/...",
        "//netos/services/fboss_wedge_agent/...",
    ],
)
