load(
    "//fboss/agent/fbpkg:test_artifacts.bzl",
    "get_all_agent_test_path_actions",
    "get_all_fsdb_integration_test_path_actions",
    "get_all_hw_test_path_actions",
    "get_all_invariant_test_path_actions",
    "get_all_link_test_path_actions",
)
load("//fboss/build:fbpkg.bzl", "fboss_fbpkg_builder")
# load("//fboss/agent/fbpkg:agent.bzl", "get_all_wedge_agent_csco_path_actions", "get_all_wedge_agent_dnx_path_actions", "get_all_wedge_agent_path_actions")

oncall("fboss_agent_push")

# TODO: reenable these once they have parity with cfgr pkgs, including test_artifacts

# fbpkg.builder(
#     name = "neteng.fboss.wedge_agent",
#     override_log_paths = [
#         "fboss/agent",
#         "fboss/lib",
#         "neteng/fboss/tools/wrapper_scripts",
#     ],
#     path_actions = get_all_wedge_agent_path_actions(),
#     split_debuginfo = True,
# )

# fbpkg.builder(
#     name = "neteng.fboss.wedge_agent_dnx",
#     override_log_paths = [
#         "fboss/agent",
#         "fboss/lib",
#         "neteng/fboss/tools/wrapper_scripts",
#     ],
#     path_actions = get_all_wedge_agent_dnx_path_actions(),
#     split_debuginfo = True,
# )

# fbpkg.builder(
#     name = "neteng.fboss.wedge_agent_csco",
#     override_log_paths = [
#         "fboss/agent",
#         "fboss/lib",
#         "neteng/fboss/tools/wrapper_scripts",
#     ],
#     path_actions = get_all_wedge_agent_csco_path_actions(),
#     split_debuginfo = True,
# )

fboss_fbpkg_builder(
    name = "neteng.fboss.wedge_agent.test_artifacts.hw_test",
    buck_modes = [
        "opt-asan",
    ],
    override_log_paths = ["fboss/agent"],
    path_actions = get_all_hw_test_path_actions(),
)

fboss_fbpkg_builder(
    name = "neteng.fboss.wedge_agent.test_artifacts.agent_test",
    buck_modes = [
        "opt-asan",
    ],
    override_log_paths = ["fboss/agent"],
    path_actions = get_all_agent_test_path_actions(),
)

fboss_fbpkg_builder(
    name = "neteng.fboss.wedge_agent.test_artifacts.link_test",
    buck_modes = [
        "opt-asan",
    ],
    override_log_paths = ["fboss/agent"],
    path_actions = get_all_link_test_path_actions(),
)

fboss_fbpkg_builder(
    name = "neteng.fboss.wedge_agent.test_artifacts.fsdb_integration_test",
    buck_modes = [
        "opt-asan",
    ],
    override_log_paths = ["fboss/agent"],
    path_actions = get_all_fsdb_integration_test_path_actions(),
)

fboss_fbpkg_builder(
    name = "neteng.fboss.wedge_agent.test_artifacts.invariant_test",
    buck_modes = [
        "opt-asan",
    ],
    override_log_paths = ["fboss/agent"],
    path_actions = get_all_invariant_test_path_actions(),
)
