load("@fbcode_macros//build_defs:python_unittest.bzl", "python_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_distro")

python_unittest(
    name = "test_package",
    srcs = ["test_package.py"],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/oss/scripts:package_lib",
    ],
)

python_unittest(
    name = "test_platform_descriptor_utils",
    srcs = ["test_platform_descriptor_utils.py"],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/oss/scripts:platform_descriptor_utils",
    ],
)

python_unittest(
    name = "test_getdeps_fallback_mirror",
    srcs = ["test_getdeps_fallback_mirror.py"],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/oss/scripts:getdeps_fallback_mirror_lib",
    ],
)

python_unittest(
    name = "test_npu_sdk_utils",
    srcs = ["test_npu_sdk_utils.py"],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/oss/scripts:npu_sdk_utils_lib",
    ],
)
