load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_agent_push")

cpp_unittest(
    name = "switch_asic_tests",
    srcs = [
        "Jericho3AsicTests.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent/hw/switch_asics:switch_asics",
    ],
)
