load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_oss")

cpp_unittest(
    name = "cmd_config_test",
    srcs = [
        "BgpConfigSessionTest.cpp",
        "CmdConfigAppliedInfoTest.cpp",
        "CmdConfigHistoryTest.cpp",
        "CmdConfigInterfaceSwitchportAccessVlanTest.cpp",
        "CmdConfigInterfaceTest.cpp",
        "CmdConfigL2LearningModeTest.cpp",
        "CmdConfigQosBufferPoolTest.cpp",
        "CmdConfigReloadTest.cpp",
        "CmdConfigSessionCommitTest.cpp",
        "CmdConfigSessionDiffTest.cpp",
        "CmdConfigSessionTest.cpp",
        "CmdConfigTestBase.cpp",
        "CmdConfigVlanPortTaggingModeTest.cpp",
        "CmdConfigVlanStaticMacTest.cpp",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//third-party/googletest:gmock",
        "//fboss/cli/fboss2:cli_metadata-cpp2-types",
        "//fboss/cli/fboss2:cmd-common-utils",
        "//fboss/cli/fboss2:fboss2-config-lib",
        "//fboss/cli/fboss2:fboss2-lib",
        "//fboss/cli/fboss2/test:cmd_test_utils",
        "//folly:file_util",
        "//folly/json:dynamic",
    ],
    external_deps = [
        ("boost", None, "boost_filesystem"),
    ],
)
