load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_oss")

cpp_unittest(
    name = "cmd_config_test",
    srcs = [
        "BgpConfigSessionTest.cpp",
        "CmdConfigAppliedInfoTest.cpp",
        "CmdConfigArpTest.cpp",
        "CmdConfigHistoryTest.cpp",
        "CmdConfigInterfaceIpv6NdpTest.cpp",
        "CmdConfigInterfaceSwitchportAccessVlanTest.cpp",
        "CmdConfigInterfaceTest.cpp",
        "CmdConfigL2LearningModeTest.cpp",
        "CmdConfigMacAgingTimeTest.cpp",
        "CmdConfigPtpTransparentClockTest.cpp",
        "CmdConfigQosBufferPoolTest.cpp",
        "CmdConfigReloadTest.cpp",
        "CmdConfigSessionCommitTest.cpp",
        "CmdConfigSessionDiffTest.cpp",
        "CmdConfigSessionTest.cpp",
        "CmdConfigTestBase.cpp",
        "CmdConfigVlanDefaultTest.cpp",
        "CmdConfigVlanManagerTest.cpp",
        "CmdConfigVlanPortTaggingModeTest.cpp",
        "CmdConfigVlanStaticMacTest.cpp",
        "CmdDeleteInterfaceIpv6NdpTest.cpp",
        "ConfigSessionSystemdTest.cpp",
    ],
    headers = [
        "MockFbossServiceUtil.h",
        "MockSystemdInterface.h",
    ],
    network_access = network_access_utils.all(),
    deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//third-party/googletest:gmock",
        "//fboss/agent:agent_config-cpp2-types",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/cli/fboss2:cli_metadata-cpp2-types",
        "//fboss/cli/fboss2:cmd-common-utils",
        "//fboss/cli/fboss2:fboss2-config-lib",
        "//fboss/cli/fboss2:fboss2-lib",
        "//fboss/cli/fboss2/test:cmd_test_utils",
        "//folly:dynamic",
        "//folly:file_util",
        "//folly/json:dynamic",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
    external_deps = [
        ("boost", None, "boost_filesystem"),
    ],
)
