/*
 *  Copyright (c) 2004-present, Facebook, Inc.
 *  All rights reserved.
 *
 *  This source code is licensed under the BSD-style license found in the
 *  LICENSE file in the root directory of this source tree. An additional grant
 *  of patent rights can be found in the PATENTS file in the same directory.
 *
 */

#include <gtest/gtest.h>
#include <algorithm>
#include <cstddef>

#include "fboss/agent/FbossError.h"
#include "fboss/agent/gen-cpp2/switch_config_types.h"
#include "fboss/agent/types.h"
#include "fboss/cli/fboss2/commands/config/vlan/VlanManager.h"
#include "fboss/cli/fboss2/session/ConfigSession.h"
#include "fboss/cli/fboss2/test/config/CmdConfigTestBase.h"

using namespace ::testing;

namespace facebook::fboss {

class VlanManagerTestFixture : public CmdConfigTestBase {
 public:
  VlanManagerTestFixture()
      : CmdConfigTestBase(
            "fboss2_vlan_manager_test_%%%%-%%%%-%%%%-%%%%",
            R"({
  "sw": {
    "vlans": [
      {
        "id": 100,
        "name": "default"
      }
    ]
  }
})") {}
};

// ============================================================================
// Tests for VlanManager::createVlan
// ============================================================================

TEST_F(VlanManagerTestFixture, createVlanNewVlan) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(200));

  EXPECT_TRUE(created);
  EXPECT_NE(vlan, nullptr);
  EXPECT_EQ(*vlan->id(), 200);
}

TEST_F(VlanManagerTestFixture, createVlanAlreadyExists) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(100));

  EXPECT_FALSE(created);
  EXPECT_NE(vlan, nullptr);
  EXPECT_EQ(*vlan->id(), 100);
  // Should not create a duplicate
  int count = 0;
  for (const auto& v : *swConfig.vlans()) {
    if (*v.id() == 100) {
      ++count;
    }
  }
  EXPECT_EQ(count, 1);
}

TEST_F(VlanManagerTestFixture, createVlanSetsCorrectId) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  VlanManager::createVlan(swConfig, VlanID(300));

  auto it = std::find_if(
      swConfig.vlans()->cbegin(),
      swConfig.vlans()->cend(),
      [](const auto& vlan) { return *vlan.id() == 300; });
  ASSERT_NE(it, swConfig.vlans()->cend());
  EXPECT_EQ(*it->id(), 300);
}

TEST_F(VlanManagerTestFixture, createVlanSetsAutoGeneratedName) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  VlanManager::createVlan(swConfig, VlanID(42));

  auto it = std::find_if(
      swConfig.vlans()->cbegin(),
      swConfig.vlans()->cend(),
      [](const auto& vlan) { return *vlan.id() == 42; });
  ASSERT_NE(it, swConfig.vlans()->cend());
  EXPECT_EQ(*it->name(), "Vlan42");
}

TEST_F(VlanManagerTestFixture, createVlanSetsRoutableFalse) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  VlanManager::createVlan(swConfig, VlanID(500));

  auto it = std::find_if(
      swConfig.vlans()->cbegin(),
      swConfig.vlans()->cend(),
      [](const auto& vlan) { return *vlan.id() == 500; });
  ASSERT_NE(it, swConfig.vlans()->cend());
  EXPECT_FALSE(*it->routable());
}

TEST_F(VlanManagerTestFixture, createVlanDoesNotSaveConfig) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();
  size_t initialSize = swConfig.vlans()->size();

  VlanManager::createVlan(swConfig, VlanID(999));

  // VLAN is added to in-memory config, not yet persisted
  EXPECT_EQ(swConfig.vlans()->size(), initialSize + 1);
}

TEST_F(VlanManagerTestFixture, createVlanAlsoCreatesInterface) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  VlanManager::createVlan(swConfig, VlanID(400));

  auto intfIt = std::find_if(
      swConfig.interfaces()->cbegin(),
      swConfig.interfaces()->cend(),
      [](const auto& intf) { return *intf.vlanID() == 400; });
  ASSERT_NE(intfIt, swConfig.interfaces()->cend());
  EXPECT_EQ(*intfIt->intfID(), 400);
  EXPECT_EQ(*intfIt->routerID(), 0);
  EXPECT_EQ(*intfIt->name(), "fboss400");
}

TEST_F(VlanManagerTestFixture, createVlanDoesNotDuplicateInterface) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();
  size_t initialIntfSize = swConfig.interfaces()->size();

  // Creating an existing VLAN should not add a new interface
  VlanManager::createVlan(swConfig, VlanID(100));

  EXPECT_EQ(swConfig.interfaces()->size(), initialIntfSize);
}

// ============================================================================
// Tests for VlanManager::createVlan with existing/new VLANs
// ============================================================================

TEST_F(VlanManagerTestFixture, createVlanReturnsExistingVlan) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(100));

  EXPECT_FALSE(created);
  EXPECT_NE(vlan, nullptr);
  EXPECT_EQ(*vlan->id(), 100);
  EXPECT_EQ(*vlan->name(), "default");
}

TEST_F(VlanManagerTestFixture, createVlanCreatesNewVlan) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(777));

  EXPECT_TRUE(created);
  EXPECT_NE(vlan, nullptr);
  EXPECT_EQ(*vlan->id(), 777);
  EXPECT_EQ(*vlan->name(), "Vlan777");
  EXPECT_FALSE(*vlan->routable());
}

// ============================================================================
// Tests for VlanManager::createVlan sorted insertion
// ============================================================================

TEST_F(VlanManagerTestFixture, createVlanInsertsSorted) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  // Start with VLAN 100 (from fixture), add VLANs in non-sorted order
  VlanManager::createVlan(swConfig, VlanID(300));
  VlanManager::createVlan(swConfig, VlanID(50));
  VlanManager::createVlan(swConfig, VlanID(200));
  VlanManager::createVlan(swConfig, VlanID(150));

  // Verify VLANs are in sorted order: 50, 100, 150, 200, 300
  ASSERT_EQ(swConfig.vlans()->size(), 5);
  EXPECT_EQ(*swConfig.vlans()->at(0).id(), 50);
  EXPECT_EQ(*swConfig.vlans()->at(1).id(), 100);
  EXPECT_EQ(*swConfig.vlans()->at(2).id(), 150);
  EXPECT_EQ(*swConfig.vlans()->at(3).id(), 200);
  EXPECT_EQ(*swConfig.vlans()->at(4).id(), 300);
}

TEST_F(VlanManagerTestFixture, createVlanInsertsAtBeginning) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  // Start with VLAN 100, add a smaller one
  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(10));

  EXPECT_TRUE(created);
  ASSERT_GE(swConfig.vlans()->size(), 2);
  // VLAN 10 should be inserted at the beginning
  EXPECT_EQ(*swConfig.vlans()->at(0).id(), 10);
  EXPECT_EQ(*swConfig.vlans()->at(1).id(), 100);
}

TEST_F(VlanManagerTestFixture, createVlanInsertsAtEnd) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  // Start with VLAN 100, add a larger one
  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(500));

  EXPECT_TRUE(created);
  ASSERT_GE(swConfig.vlans()->size(), 2);
  // VLAN 500 should be inserted at the end
  EXPECT_EQ(*swConfig.vlans()->back().id(), 500);
}

TEST_F(VlanManagerTestFixture, createVlanInsertsInMiddle) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  // Create VLANs 50 and 200 first
  VlanManager::createVlan(swConfig, VlanID(50));
  VlanManager::createVlan(swConfig, VlanID(200));

  // Now insert 100 in the middle
  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(100));

  EXPECT_FALSE(created); // VLAN 100 already exists from fixture
  ASSERT_GE(swConfig.vlans()->size(), 3);

  // Verify order: 50, 100, 200
  EXPECT_EQ(*swConfig.vlans()->at(0).id(), 50);
  EXPECT_EQ(*swConfig.vlans()->at(1).id(), 100);
  EXPECT_EQ(*swConfig.vlans()->at(2).id(), 200);
}

TEST_F(
    VlanManagerTestFixture,
    createVlanHandlesInterfaceIdConflictWithDifferentVlan) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  // First, manually create an interface with ID 200 that belongs to VLAN 100
  cfg::Interface manualIntf;
  manualIntf.intfID() = 200;
  manualIntf.routerID() = 0;
  manualIntf.vlanID() = 100; // Belongs to VLAN 100, not 200
  manualIntf.name() = "manual_intf_200";
  manualIntf.ipAddresses() = {};
  swConfig.interfaces()->push_back(manualIntf);

  // Now create VLAN 200. This should create an interface for VLAN 200,
  // but since interface ID 200 is taken, it should use 5000 + 200 = 5200
  // to avoid future conflicts.
  auto [created, vlan] = VlanManager::createVlan(swConfig, VlanID(200));

  EXPECT_TRUE(created);
  ASSERT_NE(vlan, nullptr);
  EXPECT_EQ(*vlan->id(), 200);

  // Find the interface for VLAN 200
  auto intfIt = std::find_if(
      swConfig.interfaces()->cbegin(),
      swConfig.interfaces()->cend(),
      [](const auto& intf) { return *intf.vlanID() == 200; });

  ASSERT_NE(intfIt, swConfig.interfaces()->cend());
  // The interface ID should be 5200 (5000 + 200) to avoid future conflicts
  EXPECT_EQ(*intfIt->intfID(), 5200);
  EXPECT_EQ(*intfIt->vlanID(), 200);

  // Verify the original manual interface is unchanged
  auto manualIntfIt = std::find_if(
      swConfig.interfaces()->cbegin(),
      swConfig.interfaces()->cend(),
      [](const auto& intf) { return *intf.intfID() == 200; });

  ASSERT_NE(manualIntfIt, swConfig.interfaces()->cend());
  EXPECT_EQ(*manualIntfIt->vlanID(), 100); // Still belongs to VLAN 100
}

TEST_F(VlanManagerTestFixture, createVlanThrowsWhenBothInterfaceIdsAreUsed) {
  setupTestableConfigSession();
  auto& swConfig = *ConfigSession::getInstance().getAgentConfig().sw();

  // Create two interfaces that will block both the normal and
  // conflict-resolution IDs for VLAN 200:
  // - Interface ID 200 (normal) belongs to VLAN 100
  // - Interface ID 5200 (5000 + 200, conflict resolution) belongs to VLAN 300
  cfg::Interface intf1;
  intf1.intfID() = 200;
  intf1.routerID() = 0;
  intf1.vlanID() = 100;
  intf1.name() = "intf_200_vlan_100";
  intf1.ipAddresses() = {};
  swConfig.interfaces()->push_back(intf1);

  cfg::Interface intf2;
  intf2.intfID() = 5200; // 5000 + 200
  intf2.routerID() = 0;
  intf2.vlanID() = 300;
  intf2.name() = "intf_5200_vlan_300";
  intf2.ipAddresses() = {};
  swConfig.interfaces()->push_back(intf2);

  // Now try to create VLAN 200. This should throw because both interface IDs
  // (200 and 5200) are already taken.
  EXPECT_THROW(
      VlanManager::createVlan(swConfig, VlanID(200)),
      facebook::fboss::FbossError);
}

} // namespace facebook::fboss
