// @generated SignedSource<<13a9ba2bad59c7cc387620e36f246cb4>>
// DO NOT EDIT THIS FILE MANUALLY!
// This file is a mechanical copy of the version in the configerator repo. To
// modify it, edit the copy in the configerator repo instead and copy it over by
// running the following in your fbcode directory:
//
// configerator-thrift-updater neteng/fboss/thrift/common.thrift
// This thrift file is synced to fbcode and the FBOSS OSS repo (https://github.com/facebook/fboss).
// After making changes, run: configerator-thrift-updater neteng/fboss/thrift/common.thrift

include "thrift/annotation/thrift.thrift"
include "thrift/annotation/scope.thrift"

package "facebook.com/neteng/fboss/common"

namespace go configerator.structs.neteng.fboss.thrift.common
namespace py neteng.fboss.configerator.common
namespace py3 neteng.fboss.configerator
namespace py.asyncio neteng.fboss.asyncio.configerator.common

/**
 * Annotation to enable skipping thrift cow for a struct or field.
 */
@scope.Field
@scope.Struct
@thrift.RuntimeAnnotation
struct AllowSkipThriftCow {}
