load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "invariant_agent_tests",
    srcs = [
        "ProdAgentTests.cpp",
        "ProdInvariantTests.cpp",
    ],
    link_whole = True,
    # Will need symbols from bcm, sai layers. Those
    # will come when we build bcm/sai link test bins
    undefined_symbols = True,
    exported_deps = [
        "//fboss/agent:agent_features",
        "//fboss/agent:asic_utils",
        "//fboss/agent:core",
        "//fboss/agent:handler",
        "//fboss/agent:load_agent_config",
        "//fboss/agent:main-common",
        "//fboss/agent:route_update_wrapper",
        "//fboss/agent:setup_thrift",
        "//fboss/agent:validated_shell_commands-cpp2-types",
        "//fboss/agent/hw/test:config_factory",
        "//fboss/agent/hw/test:hw_copp_utils",
        "//fboss/agent/hw/test:hw_packet_utils",
        "//fboss/agent/hw/test:hw_qos_utils",
        "//fboss/agent/hw/test:load_balancer_utils",
        "//fboss/agent/hw/test:prod_config_factory",
        "//fboss/agent/state:state",
        "//fboss/agent/state:state_utils",
        "//fboss/agent/test:agent_ensemble_test",
        "//fboss/agent/test:ecmp_helper",
        "//fboss/agent/test/utils:acl_test_utils",
        "//fboss/agent/test/utils:dscp_marking_utils",
        "//fboss/agent/test/utils:queue_per_host_test_utils",
        "//fboss/lib/config:fboss_config_utils",
        "//folly/gen:base",
    ],
)
