load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "thrift_client_utils",
    srcs = ["ThriftClientUtils.cpp"],
    headers = ["ThriftClientUtils.h"],
    deps = [
        "//common/network:util",
        "//thrift/lib/cpp2/async:rocket_client_channel",
    ],
    exported_deps = ["//fboss/agent/if:test_ctrl-cpp2-clients"],
)
