load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_agent_push")

cpp_unittest(
    name = "fsdb_client_tests",
    srcs = [
        "FsdbPubSubManagerTest.cpp",
        "FsdbPublisherTest.cpp",
        "FsdbStreamClientTest.cpp",
    ],
    deps = [
        "//fb303:service_data",
        "//fboss/fsdb/client:fsdb_pub_sub",
        "//fboss/fsdb/client:fsdb_stream_client",
        "//fboss/fsdb/common:flags",
        "//fboss/fsdb/tests/client:fsdb_test_clients",
        "//fboss/lib:common_utils",
        "//fboss/lib/thrift_service_client:thrift-service-client",
        "//folly/coro:async_generator",
        "//folly/coro:async_pipe",
        "//folly/futures:core",
        "//folly/io/async:scoped_event_base_thread",
        "//folly/logging:logging",
    ],
)

cpp_unittest(
    name = "fsdb_sub_manager_test",
    srcs = [
        "FsdbSubManagerTest.cpp",
    ],
    deps = [
        "//fboss/fsdb/client:fsdb_cow_state_sub_manager",
        "//fboss/fsdb/client:fsdb_cow_stats_sub_manager",
        "//fboss/fsdb/client:fsdb_pub_sub",
        "//fboss/fsdb/common:utils",
        "//fboss/fsdb/oper:extended_path_builder",
        "//fboss/fsdb/tests/utils:fsdb_test_server",
        "//fboss/lib:common_utils",
        "//fboss/lib/thrift_service_client:thrift-service-client",
        "//folly/logging:init",
        "//folly/logging:log_level",
        "//folly/logging:logging",
    ],
)
