load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_agent_push")

cpp_unittest(
    name = "fsdb_cgo_wrapper_test",
    srcs = [
        "FsdbCgoWrapperTest.cpp",
    ],
    network_access = network_access_utils.all(),
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/fsdb/client:fsdb_pub_sub",
        "//fboss/fsdb/client/cgo:fsdb_cgo_pub_sub_wrapper",
        "//fboss/fsdb/if:fsdb_oper-cpp2-types",
        "//fboss/fsdb/tests/client:fsdb_test_clients",
        "//fboss/fsdb/tests/utils:fsdb_test_server",
        "//folly/logging:logging",
    ],
)

cpp_unittest(
    name = "fsdb_cgo_wrapper_api_test",
    srcs = [
        "FsdbCgoWrapperApiTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/fsdb/client/cgo:fsdb_cgo_pub_sub_wrapper",
        "//folly/init:phase",
    ],
)
