load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_agent_push")

cpp_unittest(
    name = "connection_options_test",
    srcs = ["ConnectionOptionsTests.cpp"],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/fsdb/if:fsdb-cpp2-clients",
        "//fboss/lib/thrift_service_client:thrift-service-client",
    ],
)
