load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_platform")

# Pure (folly-only) helpers used by the platform Thrift connection acceptor:
# parsing the trusted-subnet allowlist and deciding whether a client IP is
# trusted. Split out so the security-relevant logic is unit testable without
# pulling in the Thrift server stack.
cpp_library(
    name = "platform_thrift_acceptor_util",
    headers = [
        "PlatformThriftAcceptorUtil.h",
    ],
    exported_deps = [
        "//folly:network_address",
        "//folly:string",
    ],
)

# Connection-level acceptor that admits only loopback + trusted-subnet peers.
# Header-only; consumed by the OSS runThriftService bootstrap.
cpp_library(
    name = "platform_thrift_acceptor",
    headers = [
        "PlatformThriftAcceptor.h",
    ],
    exported_deps = [
        ":platform_thrift_acceptor_util",
        "//folly:network_address",
        "//folly/io/async:async_transport",
        "//folly/logging:logging",
        "//thrift/lib/cpp2:server",
        "//wangle/acceptor:acceptor",
    ],
)

cpp_unittest(
    name = "platform_thrift_acceptor_test",
    srcs = [
        "facebook/PlatformThriftAcceptorTest.cpp",
    ],
    # Pure in-process string/IP logic; no network access needed.
    network_access = network_access_utils.none(),
    deps = [
        ":platform_thrift_acceptor",
        ":platform_thrift_acceptor_util",
        "//folly:network_address",
    ],
)

cpp_library(
    name = "expect_session",
    srcs = [
        "ExpectSession.cpp",
    ],
    headers = [
        "ExpectSession.h",
    ],
    exported_deps = [],
)

cpp_library(
    name = "platform_name_lib",
    srcs = [
        "PlatformNameLib.cpp",
    ],
    deps = [
        "//fb303:service_data",
        "//folly:string",
        "//folly/logging:logging",
    ],
    exported_deps = [
        ":platform_fs_utils",
        ":platform_utils",
    ],
)

cpp_library(
    name = "platform_utils",
    srcs = [
        "PlatformUtils.cpp",
    ],
    deps = [
        "//folly:subprocess",
        "//folly/logging:logging",
        "//folly/system:shell",
    ],
    exported_deps = [],
)

cpp_library(
    name = "platform_fs_utils",
    srcs = [
        "PlatformFsUtils.cpp",
    ],
    deps = [
        "//folly:file_util",
        "//folly:string",
        "//folly/logging:logging",
    ],
    exported_deps = [
        "//folly/portability:fcntl",
    ],
)

cpp_library(
    name = "init",
    srcs = [
        "facebook/Init.cpp",
    ],
    headers = [
        "Init.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//common/base:build_info",
        "//common/init:init",
        "//common/services/cpp:acl_checker_module",
        "//common/services/cpp:build_values",
        "//common/services/cpp:light",
        "//common/services/cpp:proc_module",
        "//common/services/cpp:proc_standalone",
        "//common/services/cpp:thrift_acl_checker_module_config",
    ],
    exported_deps = [
        "//folly:function",
        "//folly/io/async:async_signal_handler",
        "//thrift/lib/cpp2:server",
        "//thrift/lib/cpp2/async:async_processor",
    ],
    external_deps = [
        "gflags",
        ("openssl", None, "crypto"),
    ],
    exported_external_deps = [
        "gflags",
        ("openssl", None, "crypto"),
    ],
)

cpp_library(
    name = "init_cli",
    srcs = [
        "facebook/InitCli.cpp",
    ],
    headers = [
        "InitCli.h",
    ],
    deps = [
        "//common/base:build_info",
        "//folly/init:init",
    ],
    exported_deps = [],
    exported_external_deps = [
        "gflags",
    ],
)

cpp_library(
    name = "mock_platform_utils",
    headers = [
        "MockPlatformUtils.h",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gmock",
        ":platform_utils",
    ],
)

cpp_library(
    name = "mock_platform_fs_utils",
    headers = [
        "MockPlatformFsUtils.h",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gmock",
        ":platform_fs_utils",
    ],
)

cpp_library(
    name = "structured_logger",
    srcs = [
        "StructuredLogger.cpp",
    ],
    headers = [
        "StructuredLogger.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        ":platform_name_lib",
        "//folly/logging:logging",
    ],
    exported_deps = [],
)
