load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_platform")

cpp_unittest(
    name = "reboot_cause_finder_impl_test",
    srcs = [
        "RebootCauseFinderImplTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/fmt:fmt",
        "fbsource//third-party/googletest:gmock",
        "//fboss/platform/reboot_cause_finder:reboot_cause_finder_lib",
        "//folly:dynamic",
        "//folly:file_util",
        "//folly:network_address",
        "//folly:scope_guard",
        "//folly:string",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
