load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fboss_platform")

cpp_binary(
    name = "rackmon_hw_test",
    srcs = [
        "Main.cpp",
        "RackmonHwTest.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//common/services/cpp:light",
        "//fboss/platform/helpers:init",
        "//fboss/platform/rackmon:core",
        "//fboss/platform/rackmon:handler",
        "//fboss/platform/rackmon:rackmon_pls",
        "//fboss/platform/rackmon/if:rackmonsvc-cpp2-services",
        "//folly/init:init",
        "//folly/logging:init",
        "//folly/logging:logging",
        "//thrift/lib/cpp2:server",
        "//thrift/lib/cpp2/async:rocket_client_channel",
        "//thrift/lib/cpp2/util:util",
    ],
    external_deps = [
        "glog",
    ],
)
