[Service]
ExecStart=
ExecStart=/bin/bash -c 'source /opt/fboss/bin/setup_fboss_env && exec /opt/fboss/bin/platform_manager --run_once=false --config_file=/etc/fboss/fake_platform_manager.json --enable_pkg_mgmnt=false --thrift_ssl_policy=disabled'
