load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_agent_push")

cpp_library(
    name = "fboss_config_utils",
    srcs = [
        "PlatformConfigUtils.cpp",
    ],
    headers = [
        "PlatformConfigUtils.h",
    ],
    deps = [
        "//fboss/agent:fboss-error",
        "//thrift/lib/cpp/util:enum_utils",
    ],
    exported_deps = [
        "//fboss/agent:fboss-types",
        "//fboss/agent:platform_config-cpp2-types",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/lib/phy:external_phy",
        "//fboss/lib/phy:phy-cpp2-types",
    ],
)

cpp_unittest(
    name = "fboss_config_utils_tests",
    srcs = [
        "tests/PlatformConfigUtilsTests.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":fboss_config_utils",
        "//fboss/agent:fboss-error",
    ],
)

cpp_library(
    name = "port_config_utils",
    srcs = [
        "agent/PortConfigUtils.cpp",
    ],
    headers = [
        "agent/PortConfigUtils.h",
    ],
    deps = [
        "//fboss/agent:fboss-error",
        "//fboss/agent/platforms/common:platform_mapping",
    ],
    exported_deps = [
        "//fboss/agent:fboss-types",
        "//fboss/agent:switch_config-cpp2-types",
    ],
)

cpp_unittest(
    name = "port_config_utils_tests",
    srcs = [
        "agent/tests/PortConfigUtilsTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":port_config_utils",
        "//fboss/agent:fboss-error",
        "//fboss/agent:platform_config-cpp2-types",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent/platforms/common:platform_mapping",
    ],
)

cpp_library(
    name = "acl_config_utils",
    srcs = [
        "agent/AclConfigUtils.cpp",
    ],
    headers = [
        "agent/AclConfigUtils.h",
    ],
    deps = [
        "//fboss/agent:fboss-error",
        "//fboss/agent/hw/switch_asics:switch_asics",
        "//folly:cpp_attributes",
    ],
    exported_deps = [
        "//fboss/agent:switch_config-cpp2-types",
    ],
)

cpp_unittest(
    name = "acl_config_utils_tests",
    srcs = [
        "agent/tests/AclConfigUtilsTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":acl_config_utils",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent/hw/switch_asics:switch_asics",
    ],
)
