load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "path",
    srcs = [
        "Path.cpp",
    ],
    headers = [
        "Path.h",
    ],
    exported_deps = [
        "//fboss/fsdb/if:fsdb_oper-cpp2-types",
        "//folly:string",
        "//folly:unit",
    ],
)
