load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")
load("//fbpkg:fbpkg.bzl", "fbpkg")

oncall("fboss_platform")

cpp_library(
    name = "result_printer",
    srcs = [
        "ResultPrinter.cpp",
    ],
    headers = [
        "ResultPrinter.h",
    ],
    exported_deps = [
        "//fboss/platform/platform_checks:check_types-cpp2-types",
    ],
)

cpp_library(
    name = "check_runner",
    srcs = [
        "CheckRunner.cpp",
    ],
    headers = [
        "CheckRunner.h",
    ],
    deps = [
        "//folly/logging:logging",
    ],
    exported_deps = [
        "//fboss/platform/platform_checks:platform_check",
    ],
)

cpp_library(
    name = "check_environment",
    srcs = [
        "CheckEnvironment.cpp",
    ],
    headers = [
        "CheckEnvironment.h",
    ],
    deps = [
        "//fboss/platform/platform_checks:platform_name",
        "//folly:string",
        "//folly/logging:logging",
    ],
    exported_deps = [
        "//fboss/platform/platform_checks:host",
        "//fboss/platform/platform_checks:remote_host",
    ],
)

cpp_library(
    name = "check_registry",
    srcs = [
        "CheckRegistry.cpp",
    ],
    headers = [
        "CheckRegistry.h",
    ],
    deps = [
        "//fboss/platform/platform_checks:platform_checks",
    ],
    exported_deps = [
        ":check_environment",
        "//fboss/platform/platform_checks:platform_check",
    ],
)

cpp_binary(
    name = "fixmyfboss",
    srcs = [
        "main.cpp",
    ],
    deps = [
        ":check_environment",
        ":check_registry",
        ":check_runner",
        ":result_printer",
        "//folly/logging:logging",
    ],
    external_deps = [
        "CLI11",
    ],
)

fbpkg.builder(
    name = "fboss.fixmyfboss",
    architectures = ["x86_64"],
    path_actions = {
        "fixmyfboss": "//fboss/platform/fixmyfboss:fixmyfboss",
    },
)

cpp_unittest(
    name = "result_printer_test",
    srcs = [
        "tests/ResultPrinterTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        ":result_printer",
    ],
)

cpp_unittest(
    name = "check_runner_test",
    srcs = [
        "tests/CheckRunnerTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":check_runner",
    ],
)

cpp_unittest(
    name = "check_environment_test",
    srcs = [
        "tests/CheckEnvironmentTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":check_environment",
    ],
)
