#!/usr/bin/env python3
# Copyright (c) 2004-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

"""FBOSS Image Builder CLI"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from cmds.build import setup_build_command
from cmds.device import setup_device_commands
from lib.cli import CLI
from lib.logger import setup_logging


def main():
    """Main entry point for fboss-image CLI"""
    cli = CLI(description="FBOSS Distro Image CLI")

    setup_build_command(cli)
    setup_device_commands(cli)

    return cli.run(setup_logging_func=setup_logging)


if __name__ == "__main__":
    sys.exit(main())
