[Service]
ExecStart=
ExecStart=/bin/bash -c 'source /opt/fboss/bin/setup_fboss_env && exec /opt/fboss/bin/fan_service --thrift_ssl_policy=disabled --config_file=/etc/fboss/fake_platform_manager.json'
