load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_platform")

cpp_unittest(
    name = "data_corral_sw_test",
    srcs = [
        "FruPresenceExplorerTests.cpp",
        "LedManagerTests.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//fb303:service_data",
        "//fboss/lib:common_file_utils",
        "//fboss/platform/data_corral_service:led_management",
        "//folly:file_util",
        "//folly/testing:test_util",
    ],
)

cpp_unittest(
    name = "config_validator_test",
    srcs = [
        "ConfigValidatorTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/config_lib:config_lib",
        "//fboss/platform/data_corral_service:config_validator",
        "//folly/logging:logging",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
