load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_optics_phy")

cpp_unittest(
    name = "transceiver-properties-manager-test",
    srcs = [
        "TransceiverPropertiesManagerTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/agent:fboss-error",
        "//fboss/qsfp_service/module/properties:transceiver-properties-manager",
        "//folly:file_util",
        "//folly/testing:test_util",
    ],
)
