# @autodeps
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_optics_phy")

cpp_library(
    name = "morgan800cc_bsp",
    srcs = [
        "Morgan800ccBspPlatformMapping.cpp",
    ],
    headers = [
        "Morgan800ccBspPlatformMapping.h",
    ],
    exported_deps = [
        "//fboss/lib/bsp:bsp_platform_mapping-cpp2-types",
        "//fboss/lib/bsp:bsp_platform_mapping_lib",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
