load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("fboss_agent_push")

thrift_library(
    name = "lldp_config",
    languages = ["cpp2"],
    thrift_cpp2_options = "json",
    thrift_srcs = {"LldpConfig.thrift": []},
)
