load("//fboss/build:fbpkg.bzl", "fboss_fbpkg_builder")

oncall("fboss_agent_push")

fboss_fbpkg_builder(
    name = "neteng.fboss.fsdb",
    architectures = [
        "aarch64",
        "x86_64",
    ],
    path_actions = {
        "fsdb": "//fboss/fsdb/server:fsdb",
        "fsdb.service": "//neteng/fboss/fsdb:fsdb.service",
    },
)
