load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_optics_phy")

cpp_unittest(
    name = "parser_test",
    srcs = [
        "ParserTest.cpp",
    ],
    network_access = network_access_utils.none(),
    resources = [
        "test_data/test_example.csv",
    ],
    deps = [
        "//fboss/lib/bsp/bspmapping:parser",
        "//fboss/lib/if:fboss_common-cpp2-types",
        "//folly:range",
    ],
)
