load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_optics_phy")

cpp_unittest(
    name = "parser_test",
    srcs = [
        "ParserTest.cpp",
    ],
    resources = [
        "test_data/test_example.csv",
    ],
    deps = [
        "//fboss/lib/bsp/bspmapping:parser",
        "//fboss/lib/if:fboss_common-cpp2-types",
        "//folly:range",
    ],
)
