load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "tajo_punt_header",
    srcs = [
        "TajoPuntHeader.cpp",
    ],
    exported_deps = [
        "//folly/io:iobuf",
    ],
)
