load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fboss_platform")

cpp_binary(
    name = "platform_hw_test",
    srcs = [
        "PlatformHwTest.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//fboss/platform/helpers:init",
        "//fboss/platform/helpers:platform_fs_utils",
        "//fboss/platform/platform_checks:platform_checks",
        "//fboss/platform/platform_manager:config_utils",
    ],
)
