load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fboss_platform")

cpp_binary(
    name = "platform_hw_test",
    srcs = [
        "PlatformHwTest.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//fboss/platform/helpers:init",
        "//fboss/platform/weutil:fboss_eeprom_lib",
        "//fboss/platform/weutil:weutil_core",
        "//folly:network_address",
    ],
)
