#!/bin/bash

# If the process exited with return code 0, or if it was killed with
# SIGTERM, just exit immediately and let the service get restarted
# right away.
if [ "$1" == "0" -o "$2" == "15" ]; then
  echo "0" > /etc/sv/qsfp_server/exit_status
  [[ ! -e /etc/sv/qsfp_server/finish_dynamic ]] || /etc/sv/qsfp_server/finish_dynamic "0"
  exit 0
fi

echo "1" > /etc/sv/qsfp_server/exit_status
[[ ! -e /etc/sv/qsfp_server/finish_dynamic ]] || /etc/sv/qsfp_server/finish_dynamic "1"
# Other exit codes are generally unexpected.  Sleep for max_sleep seconds
# to ensure that the service doesn't restart too frequently in case it
# is in a crash loop
/bin/sleep 1

exit 0
