load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load(
    "@fbsource//tools/build_defs/testinfra:network_access_utils.bzl",
    "network_access_utils",
)

oncall("fboss_agent_push")

cpp_library(
    name = "rib_header",
    headers = glob(["*.h"]),
    exported_deps = [
        "fbsource//third-party/googletest:gtest_headers",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/agent:fboss_event_base",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent:switch_state-cpp2-types",
        "//fboss/agent/if:common-cpp2-types",
        "//fboss/agent/if:ctrl-cpp2-services",
        "//fboss/agent/state:state",
        "//fboss/lib:radix_tree",
        "//folly:network_address",
        "//folly:range",
        "//folly:synchronized",
        "//folly/json:dynamic",
    ],
    exported_external_deps = [
        ("boost", None, "boost_container"),
        "gflags",
    ],
)

cpp_library(
    name = "standalone_rib",
    srcs = [
        "ConfigApplier.cpp",
        "MySidConfigUtils.cpp",
        "RibMySidUpdater.cpp",
        "RibRouteWeightNormalizer.cpp",
        "RouteUpdater.cpp",
        "RoutingInformationBase.cpp",
        "VrfRouteTable.cpp",
    ],
    exported_deps = [
        ":network_to_route_map",
        ":nexthop_id_manager",
        "//fboss/agent:address_utils",
        "//fboss/agent:agent_features",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/agent:fboss_event_base",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent:switch_state-cpp2-types",
        "//fboss/agent:utils",
        "//fboss/agent/if:common-cpp2-types",
        "//fboss/agent/if:ctrl-cpp2-services",
        "//fboss/agent/if:ctrl-cpp2-types",
        "//fboss/agent/state:nodebase",
        "//fboss/agent/state:state",
        "//folly:conv",
        "//folly:network_address",
        "//folly:range",
        "//folly:scope_guard",
        "//folly:synchronized",
        "//folly/logging:logging",
    ],
    exported_external_deps = [
        "boost",
        ("boost", None, "boost_container"),
    ],
)

cpp_unittest(
    name = "rib_tests",
    srcs = [
        "test/FibInteractionTests.cpp",
        "test/MySidMapUpdaterTests.cpp",
        "test/NamedNextHopGroupRibTests.cpp",
        "test/NextHopIDManagerTests.cpp",
        "test/NextHopMapPopulationTests.cpp",
        "test/ReconstructRibFromSwitchStateTests.cpp",
        "test/RibLpmTests.cpp",
        "test/RibMySidUpdateTests.cpp",
        "test/RibMySidUpdaterTests.cpp",
        "test/RibRollbackTests.cpp",
        "test/RibRouteNormalizerTests.cpp",
        "test/RibToSwitchStateUpdaterTests.cpp",
        "test/RouteTests.cpp",
        "test/SerDesTests.cpp",
    ],
    network_access = network_access_utils.none(),
    test_main = "//fboss/agent/test:fboss_test_main",
    deps = [
        "fbsource//third-party/fmt:fmt",
        ":fib_updater",
        ":network_to_route_map",
        ":nexthop_id_manager",
        ":standalone_rib",
        "//common/network/if:if-cpp2-types",
        "//fboss/agent:address_utils",
        "//fboss/agent:agent_features",
        "//fboss/agent:core",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/agent:fib_helpers",
        "//fboss/agent:hwswitch_matcher",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent:switchid_scope_resolver",
        "//fboss/agent:utils",
        "//fboss/agent/hw/mock:mock",
        "//fboss/agent/if:common-cpp2-types",
        "//fboss/agent/if:ctrl-cpp2-services",
        "//fboss/agent/if:ctrl-cpp2-types",
        "//fboss/agent/if:mpls-cpp2-types",
        "//fboss/agent/state:label_forwarding_action",
        "//fboss/agent/state:state",
        "//fboss/agent/test:hw_test_handle",
        "//fboss/agent/test:label_forwarding_utils",
        "//fboss/agent/test:utils",
        "//fboss/agent/test/utils:nexthop_id_test_utils",
        "//folly:network_address",
        "//folly:scope_guard",
        "//folly/json:dynamic",
        "//folly/logging:logging",
    ],
    external_deps = [
        "gflags",
    ],
)

cpp_unittest(
    name = "config_application_tests",
    srcs = [
        "test/ConfigApplicationTests.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        ":standalone_rib",
        "//fboss/agent:fib_helpers",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent/hw/mock:mock",
        "//fboss/agent/state:state",
        "//fboss/agent/test:utils",
    ],
)

cpp_library(
    name = "network_to_route_map",
    headers = ["NetworkToRouteMap.h"],
    exported_deps = [
        "//fboss/agent:fboss-types",
        "//fboss/agent/state:state",
        "//fboss/lib:radix_tree",
        "//folly:network_address",
        "//folly/json:dynamic",
    ],
    exported_external_deps = [
        "gflags",
    ],
)

cpp_library(
    name = "fib_updater",
    srcs = [
        "FibUpdateHelpers.cpp",
        "ForwardingInformationBaseUpdater.cpp",
        "MySidMapUpdater.cpp",
        "RibToSwitchStateUpdater.cpp",
        "SwitchStateNextHopIdUpdater.cpp",
    ],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        ":network_to_route_map",
        ":nexthop_id_manager",
        ":standalone_rib",
        "//fboss/agent:agent_features",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/agent:fib_helpers",
        "//fboss/agent:switchid_scope_resolver",
        "//fboss/agent/state:nodebase",
        "//fboss/agent/state:state",
        "//folly/logging:logging",
    ],
)

cpp_library(
    # @autodeps-skip: must use :rib_header — :standalone_rib would cycle
    # through :nexthop_id_manager itself.
    name = "nexthop_id_manager",
    srcs = ["NextHopIDManager.cpp"],
    headers = ["NextHopIDManager.h"],
    deps = [
        ":rib_header",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gtest_headers",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/agent/state:state",
        "//folly:network_address",
    ],
    exported_external_deps = [
        "boost",
    ],
)
