load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_agent_push")

cpp_unittest(
    name = "service_handler_tests",
    srcs = [
        "ServiceHandlerTest.cpp",
    ],
    network_access = network_access_utils.all(),
    deps = [
        "//fb303:service_data",
        "//fboss/fsdb/common:utils",
        "//fboss/fsdb/if:fsdb_common-cpp2-types",
        "//fboss/fsdb/tests/utils:fsdb_test_server",
        "//fboss/lib:common_utils",
        "//fboss/lib/thrift_service_client:thrift-service-client",
    ],
)
