load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("fboss_agent_push")

thrift_library(
    name = "bgp_table_summary",
    languages = [
        "cpp2",
    ],
    thrift_cpp2_options = "json",
    thrift_srcs = {"bgp_table_summary.thrift": []},
    deps = [
        "//neteng/fboss/bgp/if:bgp_thrift",
    ],
)
