load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_platform")

cpp_unittest(
    name = "crc16_ccitt_test",
    srcs = [
        "Crc16ccittTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/weutil:crc16_ccitt_aug",
    ],
)

cpp_unittest(
    name = "content_validator_test",
    srcs = ["ContentValidatorTest.cpp"],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/weutil:eeprom_content_validator",
    ],
)

cpp_unittest(
    name = "config_validator_test",
    srcs = [
        "ConfigValidatorTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/weutil:config_validator",
        "//folly/logging:logging",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)

cpp_unittest(
    name = "fboss_eeprom_interface_test",
    srcs = [
        "FbossEepromInterfaceTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/weutil:fboss_eeprom_lib",
        "//fboss/platform/weutil/if:eeprom_contents-cpp2-types",
        "//folly:file_util",
        "//folly/testing:test_util",
    ],
)

cpp_unittest(
    name = "config_utils_test",
    srcs = [
        "ConfigUtilsTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/weutil:config_utils_lib",
        "//folly:file_util",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)

cpp_unittest(
    name = "parser_utils_test",
    srcs = [
        "ParserUtilsTest.cpp",
    ],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/platform/weutil:crc16_ccitt_aug",
        "//fboss/platform/weutil:fboss_eeprom_lib",
        "//folly:file_util",
        "//folly/testing:test_util",
    ],
)
