load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

python_library(
    name = "thrift_clients",
    srcs = [
        "thrift_clients.py",
    ],
    deps = [
        "//fboss/agent/if:ctrl-py",
        "//fboss/qsfp_service/if:qsfp-py",
        "//thrift/lib/py:server_base",
    ],
)
