#!/usr/bin/env python3
# Copyright 2004-present Facebook. All Rights Reserved.

from neteng.fboss.ctrl.thrift_clients import FbossCtrl
from neteng.fboss.qsfp.thrift_clients import QsfpService
from thrift.python.client.sync_client_factory import get_client as get_sync_client


#################
# This class wraps the autogenerated thrift class.
# All of the functions in fboss/agent/if/ctrl.thrift get inherited into
# here.
#
# For example:
#     with PlainTextFbossAgentClientDontUseInFb(host) as client:
#        print(client.getAllPortInfo())    # dump all of the port stats


class PlainTextFbossAgentClientDontUseInFb:
    DEFAULT_PORT = 5909
    DEFAULT_HW_PORT = 5931

    def __init__(self, host, port=None, timeout=5.0):
        self.host = host
        if port is None:
            port = self.DEFAULT_PORT

        self._client = get_sync_client(
            FbossCtrl,
            host=host,
            port=port,
            timeout=timeout,
        )

    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        self._client.__exit__(type, value, traceback)

    def __getattr__(self, name):
        return getattr(self._client, name)

    def close(self):
        self._client.__exit__(None, None, None)


class QsfpServiceClient:
    DEFAULT_PORT = 5910
    DEFAULT_TIMEOUT = 10.0

    # we ignore the value of port
    def __init__(self, host, port=None, timeout=None):
        # In a box with all 32 QSFP ports populated, it takes about 7.5s right
        # now to read all 32 QSFP ports. So, put the defaut timeout to 10s.
        self.host = host

        timeout = timeout or self.DEFAULT_TIMEOUT
        self._client = get_sync_client(
            QsfpService,
            host=host,
            port=self.DEFAULT_PORT,
            timeout=timeout,
        )

    def __enter__(self):
        return self

    def __exit__(self, type, value, traceback):
        self._client.__exit__(type, value, traceback)

    def __getattr__(self, name):
        return getattr(self._client, name)

    def close(self):
        self._client.__exit__(None, None, None)
