load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fboss_platform")

cpp_binary(
    name = "led_service_hw_test",
    srcs = [
        "LedEnsemble.cpp",
        "LedServiceTest.cpp",
    ],
    headers = [
        "LedEnsemble.h",
        "LedServiceTest.h",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//common/init:init",
        "//fboss/agent:enum_utils",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/led_service:led_manager",
        "//fboss/lib:common_file_utils",
        "//folly/logging:logging",
        "//thrift/lib/cpp2/async:rocket_client_channel",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
