load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_platform")

cpp_unittest(
    name = "fan_service_sw_test",
    srcs = [
        "BspTests.cpp",
        "ConfigValidatorTest.cpp",  # bazelify: exclude
        "ControlLogicTests.cpp",
        "FsdbSensorSubscriberTests.cpp",  # bazelify: exclude
        "OvertempTests.cpp",
        "PidLogicTests.cpp",  # bazelify: exclude
        "SensorDataTests.cpp",  # bazelify: exclude
    ],
    deps = [
        "fbsource//third-party/googletest:gmock",
        "//fboss/agent:fboss-error",
        "//fboss/platform/config_lib:config_lib",
        "//fboss/platform/fan_service:config_validator",
        "//fboss/platform/fan_service:core",
        "//fboss/platform/fan_service:pid_logic_library",
        "//fboss/platform/fan_service/if:fan_service-cpp2-types",
        "//folly/logging:logging",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
