load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fboss_agent")

python_library(
    name = "mimic_config_gen_lib",
    srcs = [
        "defs.py",
        "discovery.py",
        "forge.py",
        "generate.py",
        "policydb.py",
        "verify.py",
    ],
    deps = [
        "//configerator/distribution/api/py:configerator_client",
        "//configerator/structs/neteng/netwhoami:netwhoami-python-types",
        "//configerator/structs/neteng/policydb:resources-python-types",
        "//neteng/netwhoami/lib/py:matcher",
        "//thrift/lib/python:types",
    ],
)
