#!/bin/bash
# Set up sccache for distributed compilation with Bazel.
#
# Creates compiler wrapper scripts that route compilation through sccache,
# and writes a .bazel.d/sccache.bazelrc file with the necessary Bazel flags.
# The main .bazelrc imports this file via try-import.
#
# Configuration: set SCCACHE_SCHEDULER_HOST and SCCACHE_AUTH_TOKEN in
# fboss/oss/scripts/fboss-build.env (see fboss-build.env.example).
#
# Usage:
#   fboss/oss/scripts/bazel-sccache-setup.sh
#   bazel build //fboss/...  # sccache is picked up via .bazelrc try-import

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
BAZEL_D="$REPO_ROOT/.bazel.d"
mkdir -p "$BAZEL_D"
SCCACHE_RC="$BAZEL_D/sccache.bazelrc"
# Clean up legacy .bazelrc.sccache if it exists
rm -f "$REPO_ROOT/.bazelrc.sccache"

# Source site-specific configuration if present.
ENV_FILE="$SCRIPT_DIR/fboss-build.env"
if [ -f "$ENV_FILE" ]; then
  # shellcheck source=/dev/null
  source "$ENV_FILE"
fi

# Make sure if OOM that the build gets the short end of the stick.
echo 1000 >/proc/self/oom_score_adj

# Detect if distributed sccache is available.
# SCCACHE_SCHEDULER_HOST can be set in fboss-build.env or the environment.
SCCACHE_SCHEDULER_HOST="${SCCACHE_SCHEDULER_HOST:-}"
if [ -z "$SCCACHE_SCHEDULER_HOST" ]; then
  rm -f "$SCCACHE_RC"
  exit 0
fi
if ! timeout 1 bash -c ">/dev/tcp/$SCCACHE_SCHEDULER_HOST/10600" 2>/dev/null; then
  echo "No sccache scheduler found at $SCCACHE_SCHEDULER_HOST, skipping sccache"
  rm -f "$SCCACHE_RC"
  exit 0
fi

# Generate sccache-dist.toml from environment variables.
SCCACHE_CONF="$BAZEL_D/sccache-dist.toml"
cat >"$SCCACHE_CONF" <<TOML
[dist]
scheduler_url = "http://${SCCACHE_SCHEDULER_HOST}:10600"
${SCCACHE_EXTRA_DIST_CONFIG:-}
[dist.auth]
type = "token"
token = "${SCCACHE_AUTH_TOKEN:-}"
TOML
export SCCACHE_CONF
export SCCACHE_ERROR_LOG="/tmp/sccache.log"
export SCCACHE_LOG=info

# If sccache is already running in distributed mode with the right config, skip restart.
if [ -f "$SCCACHE_RC" ] && SCCACHE_CONF="$SCCACHE_CONF" sccache --dist-status 2>/dev/null | grep -q scheduler_url; then
  echo "sccache distributed compilation already active"
  exit 0
fi

echo "Using distributed sccache: $SCCACHE_SCHEDULER_HOST"

# Stop any existing sccache server before reconfiguring.
sccache --stop-server >/dev/null 2>&1 || true

# Verify distributed sccache works
sccache --start-server >/dev/null 2>&1 || true
if sccache --dist-status 2>/dev/null | grep -q Disabled; then
  echo "ERROR: distributed sccache not working" >&2
  sccache --stop-server >/dev/null 2>&1 || true
  rm -f "$SCCACHE_RC"
  exit 1
fi

# Calculate parallelism. With distributed sccache, compilation runs on
# remote servers so local RAM is mainly used for preprocessing and linking.
# Match the cmake build's approach: nproc * 20 compile jobs.
NPROC=$(nproc)
JOBS=$((NPROC * 20))
[ "$JOBS" -lt 4 ] && JOBS=4

# Read machine RAM in MB for Bazel's resource pool.
# .bazelrc declares each CppLink action needs 11000 MB via
# --modify_execution_info; Bazel uses SERVER_RAM_MB to decide how many
# links to run concurrently (floor(RAM / 11000)).
SERVER_RAM_MB=$(free -m | awk '/^Mem:/{print $2}')

# Write .bazelrc.sccache that overrides the compiler settings.
# The main .bazelrc uses try-import to pick this up.
cat >"$SCCACHE_RC" <<EOF
# Auto-generated by bazel-sccache-setup.sh -- do not edit
# Overrides compiler to use sccache for distributed compilation.
build --repo_env=CC=$SCRIPT_DIR/sccache-clang
build --repo_env=CXX=$SCRIPT_DIR/sccache-clang++
build --action_env=SCCACHE_CONF=$SCCACHE_CONF
build --action_env=SCCACHE_ERROR_LOG=/tmp/sccache.log
build --action_env=SCCACHE_LOG=info
build --jobs=$JOBS
# Tell Bazel we have many more CPUs than physically present, since sccache
# dispatches compilation to remote servers. Without this, Bazel caps
# concurrent actions at HOST_CPUS regardless of --jobs.
build --local_resources=cpu=$JOBS
# Override the default memory pool with actual machine RAM. Combined with
# --modify_execution_info=CppLink=+resources:memory:11000 in .bazelrc,
# this lets Bazel schedule floor($SERVER_RAM_MB / 11000) concurrent link
# jobs natively -- no flock wrapper needed.
build --local_resources=memory=$SERVER_RAM_MB
EOF

# Start the Bazel server (if not already running) so we can set its
# oom_score_adj. All processes Bazel forks (genrules, local actions) inherit
# the value from the server, so this ensures they get killed first on OOM.
BAZEL_SERVER_PID=$(bazel info server_pid 2>/dev/null)
if [ -n "$BAZEL_SERVER_PID" ]; then
  echo 1000 >/proc/$BAZEL_SERVER_PID/oom_score_adj
fi

echo "sccache distributed compilation enabled with --jobs=$JOBS"
