load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")

oncall("fboss_distro")

python_binary(
    name = "package",
    srcs = ["package.py"],
    labels = ["autodeps2_generated"],
    main_module = "fboss.oss.scripts.package",
)
