load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "mock",
    srcs = [
        "MockHwSwitch.cpp",
        "MockPlatform.cpp",
        "MockPlatformMapping.cpp",
        "MockTestHandle.cpp",
    ],
    headers = [
        "MockPlatformMapping.h",
        "MockPlatformPort.h",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gmock",
        ":pkt",
        "//fboss/agent:constants",
        "//fboss/agent:core",
        "//fboss/agent:fboss-error",
        "//fboss/agent:fboss-types",
        "//fboss/agent:handler",
        "//fboss/agent:hw_switch",
        "//fboss/agent:platform_base",
        "//fboss/agent:switch_config-cpp2-types",
        "//fboss/agent/hw/switch_asics:switch_asics",
        "//fboss/agent/platforms/common/wedge100:wedge100_platform_mapping",
        "//fboss/agent/state:state",
        "//fboss/agent/test:hw_test_handle",
        "//fboss/lib/platforms:product-info",
        "//folly:memory",
        "//folly:network_address",
        "//folly/io:iobuf",
        "//folly/json:dynamic",
        "//folly/testing:test_util",
    ],
)

cpp_library(
    name = "pkt",
    srcs = [
        "MockRxPacket.cpp",
        "MockTxPacket.cpp",
    ],
    exported_deps = [
        "//fboss/agent:packet",
        "//fboss/agent/packet:packet",
        "//fboss/agent/packet:pktutil",
        "//folly:range",
        "//folly/io:iobuf",
    ],
)
