load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")
load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_platform")

cpp_binary(
    name = "bsp_tests",
    srcs = [
        "BspTest.cpp",
        "BspTestRunner.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        ":bsp_test_environment",
        "//fboss/platform/helpers:init",
        "//fboss/platform/helpers:platform_name_lib",
        "//folly/init:init",
        "//folly/logging:logging",
    ],
)

cpp_library(
    name = "bsp_test_environment",
    srcs = [
        "BspTestEnvironment.cpp",
    ],
    exported_deps = [
        "fbsource//third-party/googletest:gtest",
        "//fboss/platform/bsp_tests:bsp_tests_config-cpp2-types",
        "//fboss/platform/config_lib:config_lib",
        "//fboss/platform/platform_manager:config_utils",
        "//fboss/platform/platform_manager:pkg_manager",
        "//fboss/platform/platform_manager:platform_manager_config-cpp2-types",
        "//folly:file_util",
        "//folly/json:dynamic",
        "//folly/logging:logging",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
