load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_optics_phy")

cpp_unittest(
    name = "build_from_xcvr_lib_test",
    srcs = [
        "BuildFromXcvrLibTest.cpp",
    ],
    resources = [
        "bsp_platform_mapping_json/sample.json",
    ],
    deps = [
        "//fboss/lib/bsp:bsp_platform_mapping-cpp2-types",
        "//fboss/lib/bsp:build_from_xcvr_lib",
        "//fboss/lib/led:led_mapping-cpp2-types",
        "//fboss/platform/config_lib:config_lib",
        "//fboss/platform/xcvr_lib:xcvr_lib",
        "//folly:file_util",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
