load("@fbcode//antlir/antlir2/bzl/feature:defs.bzl", "feature")
load("@fbcode//metalos/bzl/data_package:data_package.bzl", "data_package")
load("@fbcode_macros//build_defs:native_rules.bzl", "buck_filegroup")
load("//fbpkg:fbpkg.bzl", "fbpkg")
load("//metalos/bzl/data_package:data_package.shape.bzl", "bind_mount_t", "data_package_t")

oncall("fboss_platform")

fbpkg.builder(
    name = "fboss.platform.stack",
    expire_days = 10,
    override_log_paths = ["fboss/platform"],
    path_actions = {
        "data_corral_service": "//fboss/platform/data_corral_service:data_corral_service",
        "data_corral_service.service": "facebook/data_corral_service.service",
        "fan_service": "//fboss/platform/fan_service:fan_service",
        "fan_service.service": "facebook/fan_service.service",
        "fw_util": "//fboss/platform/fw_util:fw_util",
        "platform_manager": "//fboss/platform/platform_manager:platform_manager",
        "platform_manager.service": "facebook/platform_manager.service",
        "rackmon": "//fboss/platform/rackmon:rackmon",
        "rackmon.service": "facebook/rackmon.service",
        "sensor_service": "//fboss/platform/sensor_service:sensor_service",
        "sensor_service.service": "facebook/sensor_service.service",
        "sensor_service_client": "//fboss/platform/sensor_service:sensor_service_client",
        "showtech": "//fboss/platform/showtech:showtech",
        "weutil": "//fboss/platform/weutil:weutil",
    },
    split_debuginfo = True,
)

buck_filegroup(
    name = "configs",
    srcs = glob(["**/*.json"]),
)

data_package(
    build_fbpkg = True,
    data_package = data_package_t(
        name = "netos.datapackage.platform.cli",
        arch = None,  # None == all arches
        bind_mounts = [
            bind_mount_t(
                source = "/usr/local/bin/netos.datapackage.platform.cli",
            ),
        ],
    ),
    default_os = "centos9",
    features = [
        feature.ensure_dirs_exist(
            dirs = "/usr/local/bin/netos.datapackage.platform.cli",
        ),
        feature.install(
            src = "//fboss/platform/fw_util:fw_util",
            dst = "/usr/local/bin/netos.datapackage.platform.cli/fw_util",
            mode = "a+rx",
        ),
        feature.install(
            src = "//fboss/platform/sensor_service:sensor_service_client",
            dst = "/usr/local/bin/netos.datapackage.platform.cli/sensor_service_client",
            mode = "a+rx",
        ),
        feature.install(
            src = "//fboss/platform/showtech:showtech",
            dst = "/usr/local/bin/netos.datapackage.platform.cli/showtech",
            mode = "a+rx",
        ),
        feature.install(
            src = "//fboss/platform/weutil:weutil",
            dst = "/usr/local/bin/netos.datapackage.platform.cli/weutil",
            mode = "a+rx",
        ),
    ],
)
