load("@fbcode_macros//build_defs:cpp_binary.bzl", "cpp_binary")

oncall("fboss_platform")

cpp_binary(
    name = "fw_util_hw_test",
    srcs = [
        "FwUtilHwTest.cpp",
    ],
    deps = [
        "fbsource//third-party/googletest:gtest",
        "//fboss/platform/config_lib:config_lib",
        "//fboss/platform/fw_util:core",
        "//fboss/platform/helpers:init",
        "//thrift/lib/cpp2/protocol:protocol",
    ],
)
