load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("fboss_agent_push")

thrift_library(
    name = "asic_config_v2",
    go_thrift_namespaces = {
        "asic_config_v2.thrift": "neteng.fboss.asic_config_v2",
    },
    languages = [
        "cpp2",
        "go",
        "py3",
        "py-asyncio",
        "rust",
        "py-deprecated",
    ],
    py3_namespace = "neteng.fboss",
    py_asyncio_base_module = "neteng.fboss.asyncio",
    py_base_module = "neteng.fboss",
    thrift_cpp2_options = "json,reflection",
    thrift_py_options = "json,sort_keys",
    thrift_rust_options = [
        "deprecated_default_enum_min_i32",
        "serde",
    ],
    thrift_srcs = {"asic_config_v2.thrift": []},
)
