load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "multi_node_util",
    srcs = ["MultiNodeUtil.cpp"],
    headers = ["MultiNodeUtil.h"],
    exported_deps = [
        "//common/network:util",
        "//fboss/agent/if:ctrl-cpp2-clients",
        "//thrift/lib/cpp2/async:rocket_client_channel",
    ],
)
