load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("fboss")

thrift_library(
    name = "model",
    languages = [
        "cpp2",
    ],
    thrift_cpp2_options = "json",
    thrift_srcs = {
        "model.thrift": [],
    },
    deps = [],
)
