load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    name = "input_balance_util",
    srcs = ["InputBalanceUtil.cpp"],
    headers = ["InputBalanceUtil.h"],
    exported_deps = [
        "//fboss/agent:switch_config-cpp2-types",
    ],
)
