load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_agent_push")

cpp_unittest(
    name = "qsfp_i2c_tests",
    srcs = [
        "I2cDevIoTests.cpp",
    ],
    deps = [
        "//fboss/lib/i2c:i2c_ctrl",
        "//folly:file_util",
        "//folly/logging:logging",
        "//folly/testing:test_util",
    ],
)
