#!/bin/bash

# Exit immediately if a command exists with a non-zero status.
set -e

LOG_DIR=/var/facebook/logs/qsfp_service

# Follow symlinks in every component of the path recursively then print the
# absolute path. All but the last component must exist.
LOG_DIR_RESOLVED=$(readlink -f "$LOG_DIR")

# Short-circuit if log dir already exists. Otherwise, create it with the appropriate permissions.
test -d "$LOG_DIR_RESOLVED" || mkdir -p -m0750 "$LOG_DIR_RESOLVED"

exec svlogd -tt "$LOG_DIR_RESOLVED"
