load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")

oncall("fboss_agent_push")

cpp_library(
    # @autodeps-skip PhysicalMemory.h is owned by both :physical_memory (impl) and
    # :function_call_time_reporter (no impl); autodeps re-picks the latter. Keep :physical_memory.
    name = "fpga_device",
    srcs = ["FpgaDevice.cpp"],
    headers = [
        "FpgaDevice.h",
        "HwMemoryRegion.h",
        "HwMemoryRegister.h",
    ],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/agent:fboss-types",
        "//fboss/lib:pci_device",
        "//fboss/lib:physical_memory",
        "//folly:shared_mutex",
        "//folly/logging:logging",
    ],
)

cpp_library(
    name = "facebook_fpga",
    srcs = [
        "FbDomFpga.cpp",
        "FbFpgaRegisters.cpp",
    ],
    headers = [
        "FbDomFpga.h",
        "FbFpgaRegisters.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/agent:fboss-error",
    ],
    exported_deps = [
        ":fpga_device",
        "//folly/logging:logging",
    ],
)

cpp_library(
    name = "fb_fpga_i2c",
    srcs = [
        "FbFpgaI2c.cpp",
    ],
    headers = [
        "FbFpgaI2c.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/agent:utils",
        "//folly/futures:core",
        "//folly/logging:logging",
    ],
    exported_deps = [
        ":facebook_fpga",
        "//fboss/lib/i2c:i2c_ctrl",
        "//fboss/lib/usb:i2-api",
        "//folly:range",
        "//folly:synchronized",
        "//folly/io/async:async_base",
    ],
)

cpp_library(
    name = "fb_fpga_spi",
    srcs = [
        "FbFpgaSpi.cpp",
    ],
    headers = [
        "FbFpgaSpi.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/agent:utils",
        "//folly/futures:core",
        "//folly/logging:logging",
    ],
    exported_deps = [
        ":facebook_fpga",
        "//fboss/lib/i2c:i2c_ctrl",
        "//fboss/lib/usb:i2-api",
        "//folly:range",
        "//folly:synchronized",
        "//folly/io/async:async_base",
    ],
)

cpp_library(
    name = "multi_pim_container",
    srcs = [
        "MultiPimPlatformPimContainer.cpp",
        "MultiPimPlatformSystemContainer.cpp",
    ],
    headers = [
        "MultiPimPlatformPimContainer.h",
        "MultiPimPlatformSystemContainer.h",
    ],
    deps = [
        ":fpga_device",
        "//fb303:thread_cached_service_data",
        "//fboss/agent:fboss-error",
        "//folly:conv",
    ],
    exported_deps = [
        "//fboss/agent:fboss-types",
        "//fboss/lib/if:pim_state-cpp2-types",
        "//folly:synchronized",
    ],
)

cpp_library(
    name = "minipack_base_container",
    srcs = [
        "FbFpgaPimQsfpController.cpp",
        "MinipackBasePimContainer.cpp",
        "MinipackBaseSystemContainer.cpp",
        "MinipackLed.cpp",
    ],
    headers = [
        "FbFpgaPimQsfpController.h",
        "MinipackBasePimContainer.h",
        "MinipackBaseSystemContainer.h",
        "MinipackLed.h",
        "MinipackPimController.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/agent:fboss-error",
    ],
    exported_deps = [
        ":fb_fpga_i2c",
        ":fb_fpga_spi",
        ":fpga_device",
        ":multi_pim_container",
        "//folly:shared_mutex",
        "//folly/logging:logging",
    ],
)

cpp_library(
    name = "minipack_container",
    srcs = [
        "MinipackPimContainer.cpp",
        "MinipackSystemContainer.cpp",
    ],
    headers = [
        "MinipackPimContainer.h",
        "MinipackSystemContainer.h",
    ],
    exported_deps = [
        "fbsource//third-party/fmt:fmt",
        ":minipack_base_container",
        "//fboss/agent:fboss-error",
        "//folly:singleton",
    ],
    exported_external_deps = [
        ("libpciaccess", None, "pciaccess"),
    ],
)

cpp_library(
    name = "wedge400_i2c",
    srcs = [
        "Wedge400I2CBus.cpp",
        "Wedge400TransceiverApi.cpp",
    ],
    headers = [
        "Wedge400I2CBus.h",
        "Wedge400TransceiverApi.h",
    ],
    deps = [
        "fbsource//third-party/fmt:fmt",
        ":wedge400_fpga",
        "//fboss/agent:utils",
        "//folly/logging:logging",
    ],
    exported_deps = [
        ":fb_fpga_i2c",
        "//fboss/lib/usb:i2-api",
    ],
)

cpp_library(
    name = "wedge400_fpga",
    srcs = [
        "Wedge400Fpga.cpp",
    ],
    headers = [
        "Wedge400Fpga.h",
    ],
    deps = [
        "//fboss/agent:fboss-error",
        "//fboss/lib:pci_access",
        "//folly/logging:logging",
    ],
    exported_deps = [
        "//fboss/agent:fboss-types",
        "//fboss/lib/fpga:facebook_fpga",
        "//folly:singleton",
    ],
)
