load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")

oncall("fboss_platform")

cpp_unittest(
    name = "platform_name_lib_test",
    srcs = [
        "PlatformNameLibTest.cpp",
    ],
    deps = [
        "//fboss/platform/helpers:mock_platform_utils",
        "//fboss/platform/helpers:platform_name_lib",
    ],
)
