load("@fbcode_macros//build_defs:python_binary.bzl", "python_binary")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fboss_agent_push")

python_binary(
    name = "fboss_route",
    srcs = [
        "fboss_route.py",
    ],
    main_function = "fboss.agent.tools.fboss_route.main",
    deps = [
        "fbsource//third-party/pypi/ipaddr:ipaddr",
        "//common/network/if:if-python-types",
        "//fboss/agent/if:ctrl-python-clients",
        "//fboss/agent/if:ctrl-python-types",
        "//fboss/qsfp_service/if:qsfp-python-clients",
        "//thrift/lib/py:server_base",
    ],
)

python_library(
    name = "send_pkt_lib",
    srcs = [
        "send_pkt.py",
    ],
    deps = [
        "//fboss/py/fboss:thrift_clients",
    ],
)
