name: Test deployment

defaults:
  run:
    working-directory: ./docs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install dependencies
        run: yarn install
      - name: Test build website
        run: yarn build
