name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v7
        with:
          python-version: "3.9" # pre-commit-hooks requires Python 3.9+
      - name: Show changed files
        run: >-
          git diff --name-only
          ${{ github.event.pull_request.base.sha || github.event.before }}...${{ github.sha }}
      - uses: pre-commit/action@v3.0.1
        env:
          PRE_COMMIT_FROM_REF: ${{ github.event.pull_request.base.sha || github.event.before }}
          PRE_COMMIT_TO_REF: ${{ github.sha }}
        with:
          # Replace the default extra_args = "--all-files" since we only care
          # about the files changed by the pull request or push.
          extra_args: >-
            --from-ref ${{ github.event.pull_request.base.sha || github.event.before }}
            --to-ref ${{ github.sha }}
