load("@fbcode_macros//build_defs:cpp_unittest.bzl", "cpp_unittest")
load("@fbsource//tools/build_defs/testinfra:network_access_utils.bzl", "network_access_utils")

oncall("fboss_agent_push")

cpp_unittest(
    name = "xgs_psamp_mod_test",
    srcs = ["XgsPsampModTest.cpp"],
    network_access = network_access_utils.none(),
    deps = [
        "//fboss/agent/packet:hdr_parse_error",
        "//fboss/agent/packet:ipfix_header",
        "//fboss/agent/packet/bcm:xgs_psamp_mod",
        "//folly/container:array",
    ],
)
