load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

oncall("fboss_distro")

python_library(
    name = "builder",
    srcs = glob(["*.py"]),
    base_module = "distro_cli.builder",
    labels = ["autodeps2_generated"],
    deps = [
        "//fboss/github/fboss-image/distro_cli/lib:artifact",
        "//fboss/github/fboss-image/distro_cli/lib:constants",
        "//fboss/github/fboss-image/distro_cli/lib:download",
        "//fboss/github/fboss-image/distro_cli/lib:exceptions",
        "//fboss/github/fboss-image/distro_cli/lib:execute",
        "//fboss/github/fboss-image/distro_cli/lib:paths",
        "//fboss/github/fboss-image/distro_cli/lib/docker:docker",
    ],
)
