load("@fbcode_macros//build_defs:cpp_library.bzl", "cpp_library")
load("@fbcode_macros//build_defs:thrift_library.bzl", "thrift_library")

oncall("fboss_optics_phy")

thrift_library(
    name = "model",
    languages = [
        "cpp2",
    ],
    thrift_cpp2_options = "json",
    thrift_srcs = {"model.thrift": []},
)

cpp_library(
    name = "CmdShowInterfaceTransceiverPerformanceMonitoring",
    srcs = ["CmdShowInterfaceTransceiverPerformanceMonitoring.cpp"],
    labels = ["autodeps2_generated"],
    deps = [
        "fbsource//third-party/fmt:fmt",
        "//fboss/cli/fboss2:table-utils",
        "//fboss/qsfp_service/if:qsfp-cpp2-services",
        "//folly:string",
    ],
    exported_deps = [
        "//fboss/cli/fboss2:cmd-handler",
        "//fboss/cli/fboss2:fboss2-lib",
    ],
)
